// Code generated by protoc-gen-go. DO NOT EDIT.
// source: primitive.proto

package pipeline

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Description of the primitive.
type Primitive struct {
	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version    string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	PythonPath string `protobuf:"bytes,3,opt,name=python_path,json=pythonPath,proto3" json:"python_path,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Digest is optional, because some locally registered primitives might not have it.
	// But for all primitives published it is available and it should be provided here as well.
	Digest               string   `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Primitive) Reset()         { *m = Primitive{} }
func (m *Primitive) String() string { return proto.CompactTextString(m) }
func (*Primitive) ProtoMessage()    {}
func (*Primitive) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6fad380e09318f4, []int{0}
}

func (m *Primitive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Primitive.Unmarshal(m, b)
}
func (m *Primitive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Primitive.Marshal(b, m, deterministic)
}
func (m *Primitive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Primitive.Merge(m, src)
}
func (m *Primitive) XXX_Size() int {
	return xxx_messageInfo_Primitive.Size(m)
}
func (m *Primitive) XXX_DiscardUnknown() {
	xxx_messageInfo_Primitive.DiscardUnknown(m)
}

var xxx_messageInfo_Primitive proto.InternalMessageInfo

func (m *Primitive) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Primitive) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Primitive) GetPythonPath() string {
	if m != nil {
		return m.PythonPath
	}
	return ""
}

func (m *Primitive) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Primitive) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func init() {
	proto.RegisterType((*Primitive)(nil), "Primitive")
}

func init() { proto.RegisterFile("primitive.proto", fileDescriptor_c6fad380e09318f4) }

var fileDescriptor_c6fad380e09318f4 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0xcc,
	0xcd, 0x2c, 0xc9, 0x2c, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x6a, 0x62, 0xe4, 0xe2,
	0x0c, 0x80, 0x89, 0x09, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x31, 0x65, 0xa6, 0x08, 0x49, 0x70, 0xb1, 0x97, 0xa5, 0x16, 0x15, 0x67, 0xe6, 0xe7, 0x49, 0x30,
	0x81, 0x05, 0x61, 0x5c, 0x21, 0x79, 0x2e, 0xee, 0x82, 0xca, 0x92, 0x8c, 0xfc, 0xbc, 0xf8, 0x82,
	0xc4, 0x92, 0x0c, 0x09, 0x66, 0xb0, 0x2c, 0x17, 0x44, 0x28, 0x20, 0xb1, 0x24, 0x43, 0x48, 0x88,
	0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x05, 0x2c, 0x03, 0x66, 0x0b, 0x89, 0x71, 0xb1, 0xa5,
	0x64, 0xa6, 0xa7, 0x16, 0x97, 0x48, 0xb0, 0x82, 0x45, 0xa1, 0x3c, 0x27, 0xae, 0x28, 0x8e, 0x82,
	0xcc, 0x82, 0xd4, 0x9c, 0xcc, 0xbc, 0xd4, 0x24, 0x36, 0xb0, 0xbb, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x30, 0xb6, 0x22, 0x06, 0xaa, 0x00, 0x00, 0x00,
}
