version: 2
jobs:
  build:
    docker:
      - image: docker.uncharted.software/distil-build:latest
        auth:
          username: $UNCHARTED_DOCKER_USERNAME
          password: $UNCHARTED_DOCKER_PW
    working_directory: /go/src/github.com/uncharted-distil/distil-pipeline-server
    steps:
      - checkout
      - run:
          name: build app binary
          command: /bin/sh -c "dep ensure;go build -i"



